Repository wisemen-digital/flutter-widgets-library, pull requests merged in 2024-07, with the labels that each got.

#11 Validated text form field passed all params
  CHANGELOG.md
  lib/widgets/valided_form_text_field.dart
  pubspec.yaml
Labels: 📃 S PR

#12 Add search appbar scaffold
  CHANGELOG.md
  lib/widgets/platform_search_bar.dart
  lib/widgets/safe_area_cupertino_refresh_indicator.dart
  lib/widgets/search_appbar_scaffold.dart
  pubspec.yaml
Labels: 📃 L PR, ✨ feature

#14 Added arabic translation file
  CHANGELOG.md
  lib/l10n/intl_ar.arb
  pubspec.yaml
Labels: 📃 XS PR, ✨ feature
