Repository wisemen-digital/flutter-widgets-library, pull requests merged in 2024-10, with the labels that each got.

#17 Updated image carousel to have dismiss
  CHANGELOG.md
  lib/widgets/custom_image_carousel.dart
  lib/widgets/fullscreen_image_carousel.dart
  lib/widgets/fullscreen_image_carousel.g.dart
  pubspec.yaml
Labels: 📃 S PR

#18 A title is required
  CHANGELOG.md
  lib/widgets/custom_image_carousel.dart
  lib/widgets/fullscreen_image_carousel.dart
  pubspec.yaml
Labels: 🛠️ bugfix, 📃 XS PR

#20 `FullscreenImageCarousel`
  CHANGELOG.md
  lib/widgets/custom_image_carousel.dart
  lib/widgets/fullscreen_image_carousel.dart
  pubspec.yaml
Labels: 📃 M PR, ✨ feature

#21 Fixed issue where imageCarousel would cause an `double can't be assigned to int` error
  CHANGELOG.md
  lib/widgets/custom_image_carousel.dart
  pubspec.yaml
Labels: 🛠️ hotfix, 📃 XS PR

#22 Improved scroll behavior of fullScreenImageCarousel
  CHANGELOG.md
  lib/generated/swl_localizations.dart
  lib/generated/swl_localizations_ar.dart
  lib/generated/swl_localizations_de.dart
  lib/generated/swl_localizations_en.dart
  lib/generated/swl_localizations_es.dart
  lib/generated/swl_localizations_fr.dart
  lib/generated/swl_localizations_ja.dart
  lib/generated/swl_localizations_nl.dart
  lib/generated/swl_localizations_ro.dart
  lib/widgets/custom_image_carousel.dart
  lib/widgets/fullscreen_image_carousel.dart
  lib/widgets/valided_form_text_field.g.dart
  pubspec.yaml
Labels: 📃 L PR

#23 Bump version to 1.0.25 and add clipBehavior parameter to AnimatedClipRect
  CHANGELOG.md
  lib/widgets/animated_clip_rect.dart
Labels: 📃 XS PR

#24 Add ShowPasswordProvider to valided_form_text_field.g.dart
  CHANGELOG.md
  lib/widgets/valided_form_text_field.g.dart
  pubspec.yaml
Labels: 🛠️ bugfix, 📃 S PR

#25 Fix version in pubspec
  pubspec.yaml
Labels: 📃 XS PR, ✨ feature

#26 Lint fixes and switch inactive color
  analysis_options.yaml
  lib/platform_widgets/platform_switch.dart
  lib/widgets/custom_image_carousel.dart
  pubspec.yaml
Labels: 📃 XS PR, ✨ feature
